// tic-tac-two-vue-state/src/components/Header.vue
<script setup lang="ts">
import { useUserDataStore } from '@/stores/userData'; 
import { RouterLink, useRouter } from 'vue-router';

const router = useRouter()

const store = useUserDataStore();

</script>

<template>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Tic Tac Two</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <RouterLink class="nav-link" to="/">Home</RouterLink>
        </li>
        <li class="nav-item" v-if="store.userName.length > 0">
          <RouterLink class="nav-link" :to="{name: 'Game', params: {username: store.userName}}">Tic Tac Two</RouterLink>
        </li>
        <li v-if="store.userName.length > 0" class="nav-item">
          <a @click="() => {store.userName = ''; router.push('/');}" class="nav-link">Logout {{ store.userName }}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>

<style scoped>
</style>

// react-rest/src/components/Header.tsx
"use client";

import Link from "next/link";

export default function Header() {
  return (
	<>
    <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div className="container-fluid">
            <Link className="navbar-brand" href="/">WebApp</Link>

            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>

            <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                <ul className="navbar-nav flex-grow-1">
                    <li className="nav-item">
                        <Link className="nav-link text-dark" href="/">Home</Link>
                    </li>

                    <li className="nav-item">
                        <Link className="nav-link text-dark" href="/tag">Tags</Link>
                    </li>
				</ul>

				<ul className="navbar-nav">
                    <li className="nav-item">
                        <Link className="nav-link text-dark" href="/login">Login</Link>
                    </li>
				</ul>
			</div>
		</div>
	</nav>
	</>
  );
}
